//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.Sockets.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SocketUIControlStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SocketUIControlStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lib.Sockets.UI.Resources.SocketUIControlStrings", typeof(SocketUIControlStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string lblClear {
            get {
                return ResourceManager.GetString("lblClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        public static string lblCopyToClip {
            get {
                return ResourceManager.GetString("lblCopyToClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string lblIP {
            get {
                return ResourceManager.GetString("lblIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string lblLog {
            get {
                return ResourceManager.GetString("lblLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerMode.
        /// </summary>
        public static string lblMode {
            get {
                return ResourceManager.GetString("lblMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string lblPort {
            get {
                return ResourceManager.GetString("lblPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RX.
        /// </summary>
        public static string lblRX {
            get {
                return ResourceManager.GetString("lblRX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send data.
        /// </summary>
        public static string lblSend {
            get {
                return ResourceManager.GetString("lblSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket details.
        /// </summary>
        public static string lblSocketInfo {
            get {
                return ResourceManager.GetString("lblSocketInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/Connect.
        /// </summary>
        public static string lblStart {
            get {
                return ResourceManager.GetString("lblStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string lblStop {
            get {
                return ResourceManager.GetString("lblStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX.
        /// </summary>
        public static string lblTX {
            get {
                return ResourceManager.GetString("lblTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erases all data from the RX textbox.
        /// </summary>
        public static string tipClear {
            get {
                return ResourceManager.GetString("tipClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies the entire RX data to clipboard (may be slow if data colume is large).
        /// </summary>
        public static string tipCopyToClip {
            get {
                return ResourceManager.GetString("tipCopyToClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding to be used for text.
        /// </summary>
        public static string tipEncoding {
            get {
                return ResourceManager.GetString("tipEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send data over the socket connection.
        /// </summary>
        public static string tipSend {
            get {
                return ResourceManager.GetString("tipSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/Stop server or client connection.
        /// </summary>
        public static string tipStartStop {
            get {
                return ResourceManager.GetString("tipStartStop", resourceCulture);
            }
        }
    }
}
